#!/bin/zsh

# Profile file.  Runs on login. Environmental variables are set here.

# Adds `~/.local/bin` to $PATH
export PATH="$PATH:${$(find ~/.local/bin -type d -printf %p:)%%:}"

# Default programs:
export EDITOR="nvim"
export VISUAL="nvim"
export TERMINAL="urxvt"
export BROWSER="firefox"

# ~/ Clean-up
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

export XINITRC="${XDG_CONFIG_HOME:-$HOME/.config}/X11/xinitrc"
export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"

export HISTFILE="${XDG_CONFIG_HOME:-$HOME/.local/share}/history"
export SAVEHIST=1
export HISTSIZE=50
export LESSHISTFILE="-" # Disable creation of lesshst file

# Other program settings
# TODO

# Start graphical server if not already running and if virtual terminal <= 3
if [ -z "${DISPLAY}" ] && [ "${XDG_VTNR}" -le 3 ]; then
	exec startx "$XINITRC" &> "${XDG_CACHE_HOME:-$HOME/.cache}/startx.log"
else
	echo "NOTICE: Current settings only auto-start graphical server on first three virtual terminals."
fi
