#!/bin/sh

userresources=${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources
usermodmap=${XDG_CONFIG_HOME:-$HOME/.config}/x11/xmodmap
sysresources=/etc/x11/xinit/.Xresources
sysmodmap=/etc/x11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs
if [ -d /etc/x11/xinit/xinitrc.d ] ; then
 for f in /etc/x11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Source ~/.xprofile commands here
if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
        . "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
else
        . "$HOME/.xprofile"
fi

# Start up ssh-agent
eval $(ssh-agent -s)

# Set the delay rate for the keyboard
xset r rate 200 25

# Start i3
exec i3
